### ISSUE TITLE
Package v2 not found?

### ISSUE THREAD

**Issue by ghost** [albenik/go-serial#11]
After running the install command:

go get -u github.com/albenik/go-serial/v2

I get an error message:

package github.com/albenik/go-serial/v2: cannot find package "github.com/albenik/go-serial/v2" in any of:
        c:\go\src\github.com\albenik\go-serial\v2 (from $GOROOT)
        C:\Users\user\go\src\github.com\albenik\go-serial\v2 (from $GOPATH)

**Comment by albenik** [comment]
Please provide additional details. 
Show your `go env` output and describe how did you try to install this package (as dependency inside go module project directory or another way)

**Comment by Aukstkalnis** [comment]
This does not work because you are using GOPATH approach which is old. If you want to download go-serial to your go path, you can not select branch name. You only can use this: go get -u github.com/albenik/go-serial. Then go to this repository in your GOPATH and git checkout v2. Or copy to your workspace vendor folder.

**Comment by ghost** [comment]
go env output:
`set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\com\AppData\Local\go-build
set GOENV=C:\Users\com\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\com\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\com\AppData\Local\Temp\go-build911338490=/tmp/go-build -gno-record-gcc-switches`

I'm currently using the default GOPATH for my workspace.
I have created a project under source folder that is located in my workspace. 
I opened a terminal in viusal studio code and executed go get -u github.com/albenik/go-serial/v2

Output:

package github.com/albenik/go-serial/v2: cannot find package "github.com/albenik/go-serial/v2" in any of:
        c:\go\src\github.com\albenik\go-serial\v2 (from $GOROOT)
        C:\Users\com\go\src\github.com\albenik\go-serial\v2 (from $GOPATH)

**Comment by albenik** [comment]
@mr-nand You need to use this library with go module enabled project, not in `GOPATH` mode.
I will add a notice to README
