### ISSUE TITLE
Detect parity errors?

### ISSUE THREAD

**Issue by ghost** [albenik/go-serial#12]
Is there a way to detect parity errors?

**Comment by albenik** [comment]
What do you mean?
Please point me to any documentation about programmatically parity error detection.

**Comment by ghost** [comment]
Is it possible to detect parity errors? For instance, if the parity bit should be set given the settings and you receive data that does not have the bit set, what happens?

Most operating systems provide a way to report parity errors but not in a consistent way. Though many would support sending a replacement character in case of errors.

.net core c# supports parity errors detection.

https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netframework-4.8

**Comment by albenik** [comment]
@mr-nand Thank you for the information.
I did a little research and found that pySerial which I used as a feature source has the same issue https://github.com/pyserial/pyserial/issues/357 and it not resolved yet too.
Unfortunately, I haven't free time to research and resolve this issue by myself, so I am ready to port it from somewhere like PySerial when it will be done or accept a PR.
