### ISSUE TITLE
Why change Port from interface to struct in v2?

### ISSUE THREAD

**Issue by kmpm** [albenik/go-serial#20]
I probably have missed something here but why change the Port type from interface to struct when changing to v2?
My guess is that there were some really big benefits.
With the bugst version I was able to create a mock port for testing stuff but that would require Port to be a interface I could implement. Mocking without interfaces i much harder.

**Comment by albenik** [comment]
@kmpm You can define an Interface at your side and then mock everything you need.

And please look here https://github.com/golang/go/wiki/CodeReviewComments#interfaces

**Comment by albenik** [comment]
Actually, the library does not require an interface for itself.
