### ISSUE TITLE
Support for Android?

### ISSUE THREAD

**Issue by harenber** [albenik/go-serial#29]
Dear @albenik ,

a question (sorry for using the "Issue" feature here): I used your fine library on my Android tablet (inside of Termux) to get a connection between this device and a Bluetooth "modem". 

I had to hack the Linux code a bit and remove several calls to (on Android) unsupported features. 

My question would be: would you be interested in these changes so that your library could "officially" support Android? 

Thanks and kind regards,

 Torsten

**Comment by albenik** [comment]
Hi @harenber!
It would be great to support additional features and platforms in the library.
I will glad to integrate your code.

Thanks a lot for the suggestion!

PS
Not a problem to ask a question through issue. I saw some authors don't like this way, but not me :)

**Comment by harenber** [comment]
Thank you very much for coming back to my message @albenik . Really appreciate your openness.

Here is a diff with the 5 calls I just had to comment out to make it work (yes I know, ugly hack):

```go
diff -rU3 go-serial/serial_termsettings_linux.go go-serial.android/serial_termsettings_linux.go
--- go-serial/serial_termsettings_linux.go	2021-12-05 10:45:47.626861809 +0100
+++ go-serial.android/serial_termsettings_linux.go	2021-11-29 12:13:06.196022383 +0100
@@ -21,11 +21,11 @@
 		return nil, newOSError(err)
 	}
 
-	if s.termios.Cflag&unix.BOTHER == unix.BOTHER {
-		if s.termios, err = unix.IoctlGetTermios(p.internal.handle, unix.TCGETS2); err != nil {
-			return nil, newOSError(err)
-		}
-	}
+	// if s.termios.Cflag&unix.BOTHER == unix.BOTHER {
+	// 	if s.termios, err = unix.IoctlGetTermios(p.internal.handle, unix.TCGETS2); err != nil {
+	// 		return nil, newOSError(err)
+	// 	}
+	// }
 
 	return s, nil
 }
@@ -33,7 +33,7 @@
 func (p *Port) applyTermSettings(s *settings) error {
 	req := uint(unix.TCSETS)
 	if s.termios.Cflag&unix.BOTHER == unix.BOTHER {
-		req = unix.TCSETS2
+		//req = unix.TCSETS2
 	}
 
 	if err := unix.IoctlSetTermios(p.internal.handle, req, s.termios); err != nil {
diff -rU3 go-serial/serial_unix.go go-serial.android/serial_unix.go
--- go-serial/serial_unix.go	2021-12-05 10:45:47.626861809 +0100
+++ go-serial.android/serial_unix.go	2021-11-29 12:10:34.866022441 +0100
@@ -51,9 +51,9 @@
 	}
 
 	// Accquire exclusive access
-	if err = unix.IoctlSetInt(h, unix.TIOCEXCL, 0); err != nil {
-		return nil, newOSError(multierr.Append(err, unix.Close(h)))
-	}
+	//	if err = unix.IoctlSetInt(h, unix.TIOCEXCL, 0); err != nil {
+	//	return nil, newOSError(multierr.Append(err, unix.Close(h)))
+	//}
 
 	p := newWithDefaults(name, &port{
 		handle:           h,
@@ -107,7 +107,7 @@
 		err,
 		unix.Close(p.internal.closePipeW),
 		unix.Close(p.internal.closePipeR),
-		unix.IoctlSetInt(p.internal.handle, unix.TIOCNXCL, 0),
+		//unix.IoctlSetInt(p.internal.handle, unix.TIOCNXCL, 0),
 		unix.Close(p.internal.handle),
 	)
 
@@ -365,7 +365,7 @@
 func (p *Port) closeAndReturnError(code PortErrorCode, err error) *PortError {
 	return &PortError{code: code, causedBy: multierr.Combine(
 		err,
-		unix.IoctlSetInt(p.internal.handle, unix.TIOCNXCL, 0),
+		//unix.IoctlSetInt(p.internal.handle, unix.TIOCNXCL, 0),
 		unix.Close(p.internal.handle),
 	)}
 }
```

Please tell me if you are happy with just the diff.

Have a great Sunday!!!

**Comment by martinhpedersen** [comment]
@harenber - FYI there is a [build tag](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) `android` built into the Go toolchain. This could be very useful if you need to make code adjustments for that particular platform only.

Not sure it is applicable here, but just though I should let you know 🙂 

Complete list here: https://go.dev/src/go/build/syslist.go

**Comment by albenik** [comment]
Hi!

@harenber Thank you for the diff, and thank you @martinhpedersen for highlight a build tag.
I made changes and tagged the `v2.5.0-pre1.` version, please check it, before I close this issue.

**Comment by harenber** [comment]
Thanks @albenik . Will try it out ASAP!!!

**Comment by harenber** [comment]
Looks perfect @albenik . Code compiled fine and my tests ran without any issues. Thanks so much for your support!!!

**Comment by albenik** [comment]
Cool! Thank! I tagged the release `v2.5.0`.
