### ISSUE TITLE
cannot get PortDetails.Product

### ISSUE THREAD

**Issue by rede97** [albenik/go-serial#3]
Hi, I found a problem when i want to get PortDetails.Product (friendlyName).

[setupDiGetDeviceRegistryProperty](https://github.com/albenik/go-serial/blob/f038e3a121ba181b817104a1abfe9104f56ad8ad/enumerator/usb_windows.go#L297)
`
setupDiGetDeviceRegistryProperty(device.set, &device.data, spdrpDeviceDesc /* spdrpFriendlyName */, nil, friendlyNameP, &friendlyNameSize, nil)
`

accroding to [SetupDiGetDeviceRegistryPropertyW ](https://docs.microsoft.com/en-us/windows/desktop/api/setupapi/nf-setupapi-setupdigetdeviceregistrypropertya)
`
WINSETUPAPI BOOL SetupDiGetDeviceRegistryPropertyA(
  HDEVINFO         DeviceInfoSet,
  PSP_DEVINFO_DATA DeviceInfoData,
  DWORD            Property,
  PDWORD           PropertyRegDataType,
  PBYTE            PropertyBuffer,
  DWORD            PropertyBufferSize,
  PDWORD           RequiredSize
);
`
PropertyBufferSize is DWORD not PDOWRD,  "&friendlyNameSize" should be “friendlyNameSize", it works.

**Comment by rede97** [comment]
maybe use
`
friendlyNameSize := uint32(unsafe.Sizeof(friendlyName) - 1)
` is better than before.
refer to pyserial 
`
ctypes.sizeof(szFriendlyName) - 1
`
but i dont know why decrease size by 1.

**Comment by rede97** [comment]
result on windows 10
`
Found port: COM25
USB ID: 0403:6001
USB serial: A506CRONA
USB Product: USB Serial Port
USB Manufacturer: FTDI
Found port: COM26
USB ID: 10C4:EA60
USB serial: 0001
USB Product: Silicon Labs CP210x USB to UART Bridge
USB Manufacturer: Silicon Laboratories
`

**Comment by albenik** [comment]
@rede97 Colud you fix and test it itself and than make a PR?

**Comment by albenik** [comment]
@rede97 
> but i dont know why decrease size by 1.

Because NULL-terminated string I think

**Comment by albenik** [comment]
@rede97 Thank you!
