### ISSUE TITLE
GetPortsList panic under linux 

### ISSUE THREAD

**Issue by renathoaz** [albenik/go-serial#4]
Trying to use GetPortList and it panic

OS

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.4 LTS
> Release:	16.04
> Codename:	xenial

GO

> go version go1.11.5 linux/amd64

```
package main

import (
	"fmt"
	"log"

	"github.com/albenik/go-serial"
)

func main() {

	ports, err := serial.GetPortsList()
	if err != nil {
		log.Fatal(err)
	}
	if len(ports) == 0 {
		log.Fatal("No serial ports found!")
	}
	for _, port := range ports {
		fmt.Printf("Found port: %v\n", port)
	}

}
```

> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4c09a2]
> 
> goroutine 1 [running]:
> github.com/albenik/go-serial/unixutils.(*Pipe).Write(0x0, 0xc0000d1d17, 0x1, 0x1, 0x519000, 0xc000457c68, 0xc0000182d0)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/unixutils/pipe.go:44 +0x22
> github.com/albenik/go-serial.(*unixPort).Close.func1(0xc0003a1e80, 0x519000, 0xc000457c68)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/serial_unix.go:46 +0x5a
> github.com/albenik/go-serial.(*unixPort).Close(0xc0003a1e80, 0xc0000d1e58, 0x519000)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/serial_unix.go:60 +0x3e
> github.com/albenik/go-serial.nativeOpen(0xc000457c70, 0xa, 0xc0000d1e58, 0xc000015601, 0x5, 0xc000457c70)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/serial_unix.go:338 +0x590
> 
> github.com/albenik/go-serial.nativeGetPortsList(0x7f50f2282000, 0x0, 0xc0000386f0, 0x40c138, 0x70)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/serial_unix.go:404 +0x382
> github.com/albenik/go-serial.GetPortsList(0xc000060070, 0xc000038730, 0x40fde2, 0xc000038750, 0x45e7d6a4)
>         /home/renatho/Documentos/GoWork/src/github.com/albenik/go-serial/serial.go:111 +0x22
> main.main()
>         /home/renatho/Documentos/GoWork/src/test/main.go:17 +0x34
> exit status 2

@albenik please help me to solve this, your lib fits perfectly to what I need, because of setReadTimeout but I need the GetPortList working too, in windows and Linux.

**Comment by renathoaz** [comment]
@albenik,
I just found the problem:

on serial_unix.go
port.SetMode fails, so port.CloseSignal is never set
so it's nil. That's the reason why that it fails on my system,
The strange thing is that  I Tried it on another machine with the same specs and the error didn't came out.

But anyway  SetMode func specifically return the follow error:  input/output error
What I did to solve:

	// Send close signal to all pending reads (if any) and close signaling pipe
```
		if port.closeSignal != nil {
			if _, err := port.closeSignal.Write([]byte{0}); err != nil {
				return err
			}
			if err := port.closeSignal.Close(); err != nil {
				return err
			}
		}
```
I don't know if it's the best way to fix it, but it worked for me.

by the way:  I Add port.opened = false here:

		if err := unix.Close(port.handle); err != nil {
			return err
		}
		port.opened = false
Thank you for the modifications on the lib, it really helped me on what I need.

**Comment by albenik** [comment]
@renathoaz Thank you for your feedback.
I need some time to carefully investigate issue and solution proposed by you.

**Comment by renathoaz** [comment]
@albenik I also added support for custom baudrate on serial_unix. I made a fork, but I made changes in import path to mine fork. Anyway if you feel interested on it: https://github.com/renathoaz/go-serial

**Comment by albenik** [comment]
@renathoaz Please look at https://github.com/albenik/go-serial/commit/561c81e887da3e883822f684cba8918e8e015aaa

I made a huge refactoring on unixPort because found that you issue possible in many places. Also errors reporting (returning) was very inconsistent.

I will be very appreciate if you check this.

If it's okay I will merge it to master.

Custom baud rate on the way...

**Comment by renathoaz** [comment]
@albenik your refactoring solved the problem that I metioned here. there's no panic anymore. 
Thank you. I need to test custom baud rate, I didn't have time to do it. One thing called my attetion, on Close method your comment //NOT THREAD SAFE. why?

**Comment by albenik** [comment]
Merged

**Comment by albenik** [comment]
>  One thing called my attetion, on Close method your comment //NOT THREAD SAFE. why?

Because `unixPort.opened` field not protected this Mutex but checked in all public methods.
Calling `Close()` and other methods twice from different goroutines may result race condition.
