### ISSUE TITLE
Calling SetDTR() or SetRTS() before opening crashes in an unexpected fashion

### ISSUE THREAD

**Issue by bmuessig** [albenik/go-serial#8]
If the SetDTR() or SetRTS() functions are called before the connection is opened, the program crashes through means of a segmentation fault, due to nullpointers. This should really be mitigated by checking for nullpointer dereference ahead of time to prevent this unclean segmentation fault. A proper Go panic is prefered here.

Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4d1b85]
```

**Comment by albenik** [comment]
@bmuessig Sorry, but I didn't understand you.
How did you call `SetDTR()` with closed connection if the port instance became available only after connection, for example

```
conn := serial.Open(...)
conn.setDTR(...)
```

Please provide an example.

**Comment by bmuessig** [comment]
@albenik I am happy to clarify. Much simplified, this was the code that caused the issue:
```
package main

import "github.com/albenik/go-serial"

func main() {
        var port serial.Port

        port.SetDTR(true)
}
```

**Comment by albenik** [comment]
Yep, you right!
I just checked `os.File` implementation as example, and found that `nil` validation really used in Go with file "descriptors", so I think this is should be done similar here.
I will fix it a bit later.

Thank you.

**Comment by bmuessig** [comment]
That's great, thank you!

**Comment by albenik** [comment]
Hi @bmuessig 
Please check `github.com/albenik/go-serial/v2`
